apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - rbac.yaml
  - data.yaml
  - support.yaml
  - application.yaml
  - availability.yaml
  - gateway.yaml
